language: node_js
node_js:
  - '10'
  - '12'
cache: yarn
notifications:
  email: false
env:
  - CI=true
before_install:
  - npm config set scripts-prepend-node-path true
  - npm i -g yarn
install:
  - yarn
script:
  - yarn build
