name: automate-PRs
# The script auto merges PRs

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  automate-PRs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Specific for the project
      - run: chmod 755 ./ci/ci-test-commands.sh
      - run: ./ci/ci-test-commands.sh

  automate-PRs-merge:
    needs: automate-PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
